// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainTrackingService.Data;

#nullable disable

namespace TrainTrackingService.Migrations
{
    [DbContext(typeof(TrainTrackingContext))]
    [Migration("20260412120147_AddDataSeeder")]
    partial class AddDataSeeder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrainTrackingService.Models.ScheduleStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("ArrivalTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("time");

                    b.Property<int>("StopId")
                        .HasColumnType("int");

                    b.Property<int>("TrainScheduleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StopId");

                    b.HasIndex("TrainScheduleId");

                    b.ToTable("ScheduleStop");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalTime = new TimeSpan(0, 8, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 8, 2, 0, 0),
                            StopId = 1,
                            TrainScheduleId = 1
                        },
                        new
                        {
                            Id = 2,
                            ArrivalTime = new TimeSpan(0, 8, 15, 0, 0),
                            DepartureTime = new TimeSpan(0, 8, 17, 0, 0),
                            StopId = 2,
                            TrainScheduleId = 1
                        },
                        new
                        {
                            Id = 3,
                            ArrivalTime = new TimeSpan(0, 8, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 8, 32, 0, 0),
                            StopId = 3,
                            TrainScheduleId = 1
                        },
                        new
                        {
                            Id = 4,
                            ArrivalTime = new TimeSpan(0, 8, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 8, 2, 0, 0),
                            StopId = 1,
                            TrainScheduleId = 2
                        },
                        new
                        {
                            Id = 5,
                            ArrivalTime = new TimeSpan(0, 8, 15, 0, 0),
                            DepartureTime = new TimeSpan(0, 8, 17, 0, 0),
                            StopId = 2,
                            TrainScheduleId = 2
                        },
                        new
                        {
                            Id = 6,
                            ArrivalTime = new TimeSpan(0, 8, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 8, 32, 0, 0),
                            StopId = 3,
                            TrainScheduleId = 2
                        },
                        new
                        {
                            Id = 7,
                            ArrivalTime = new TimeSpan(0, 8, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 8, 2, 0, 0),
                            StopId = 1,
                            TrainScheduleId = 3
                        },
                        new
                        {
                            Id = 8,
                            ArrivalTime = new TimeSpan(0, 8, 15, 0, 0),
                            DepartureTime = new TimeSpan(0, 8, 17, 0, 0),
                            StopId = 2,
                            TrainScheduleId = 3
                        },
                        new
                        {
                            Id = 9,
                            ArrivalTime = new TimeSpan(0, 8, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 8, 32, 0, 0),
                            StopId = 3,
                            TrainScheduleId = 3
                        },
                        new
                        {
                            Id = 10,
                            ArrivalTime = new TimeSpan(0, 8, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 8, 2, 0, 0),
                            StopId = 1,
                            TrainScheduleId = 4
                        },
                        new
                        {
                            Id = 11,
                            ArrivalTime = new TimeSpan(0, 8, 15, 0, 0),
                            DepartureTime = new TimeSpan(0, 8, 17, 0, 0),
                            StopId = 2,
                            TrainScheduleId = 4
                        },
                        new
                        {
                            Id = 12,
                            ArrivalTime = new TimeSpan(0, 8, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 8, 32, 0, 0),
                            StopId = 3,
                            TrainScheduleId = 4
                        },
                        new
                        {
                            Id = 13,
                            ArrivalTime = new TimeSpan(0, 8, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 8, 2, 0, 0),
                            StopId = 1,
                            TrainScheduleId = 5
                        },
                        new
                        {
                            Id = 14,
                            ArrivalTime = new TimeSpan(0, 8, 15, 0, 0),
                            DepartureTime = new TimeSpan(0, 8, 17, 0, 0),
                            StopId = 2,
                            TrainScheduleId = 5
                        },
                        new
                        {
                            Id = 15,
                            ArrivalTime = new TimeSpan(0, 8, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 8, 32, 0, 0),
                            StopId = 3,
                            TrainScheduleId = 5
                        },
                        new
                        {
                            Id = 16,
                            ArrivalTime = new TimeSpan(0, 8, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 8, 2, 0, 0),
                            StopId = 1,
                            TrainScheduleId = 6
                        },
                        new
                        {
                            Id = 17,
                            ArrivalTime = new TimeSpan(0, 8, 15, 0, 0),
                            DepartureTime = new TimeSpan(0, 8, 17, 0, 0),
                            StopId = 2,
                            TrainScheduleId = 6
                        },
                        new
                        {
                            Id = 18,
                            ArrivalTime = new TimeSpan(0, 8, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 8, 32, 0, 0),
                            StopId = 3,
                            TrainScheduleId = 6
                        },
                        new
                        {
                            Id = 19,
                            ArrivalTime = new TimeSpan(0, 8, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 8, 2, 0, 0),
                            StopId = 1,
                            TrainScheduleId = 7
                        },
                        new
                        {
                            Id = 20,
                            ArrivalTime = new TimeSpan(0, 8, 15, 0, 0),
                            DepartureTime = new TimeSpan(0, 8, 17, 0, 0),
                            StopId = 2,
                            TrainScheduleId = 7
                        },
                        new
                        {
                            Id = 21,
                            ArrivalTime = new TimeSpan(0, 8, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 8, 32, 0, 0),
                            StopId = 3,
                            TrainScheduleId = 7
                        },
                        new
                        {
                            Id = 22,
                            ArrivalTime = new TimeSpan(0, 10, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 2, 0, 0),
                            StopId = 1,
                            TrainScheduleId = 8
                        },
                        new
                        {
                            Id = 23,
                            ArrivalTime = new TimeSpan(0, 10, 15, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 17, 0, 0),
                            StopId = 2,
                            TrainScheduleId = 8
                        },
                        new
                        {
                            Id = 24,
                            ArrivalTime = new TimeSpan(0, 10, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 32, 0, 0),
                            StopId = 3,
                            TrainScheduleId = 8
                        },
                        new
                        {
                            Id = 25,
                            ArrivalTime = new TimeSpan(0, 10, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 2, 0, 0),
                            StopId = 1,
                            TrainScheduleId = 9
                        },
                        new
                        {
                            Id = 26,
                            ArrivalTime = new TimeSpan(0, 10, 15, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 17, 0, 0),
                            StopId = 2,
                            TrainScheduleId = 9
                        },
                        new
                        {
                            Id = 27,
                            ArrivalTime = new TimeSpan(0, 10, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 32, 0, 0),
                            StopId = 3,
                            TrainScheduleId = 9
                        },
                        new
                        {
                            Id = 28,
                            ArrivalTime = new TimeSpan(0, 10, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 2, 0, 0),
                            StopId = 1,
                            TrainScheduleId = 10
                        },
                        new
                        {
                            Id = 29,
                            ArrivalTime = new TimeSpan(0, 10, 15, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 17, 0, 0),
                            StopId = 2,
                            TrainScheduleId = 10
                        },
                        new
                        {
                            Id = 30,
                            ArrivalTime = new TimeSpan(0, 10, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 32, 0, 0),
                            StopId = 3,
                            TrainScheduleId = 10
                        },
                        new
                        {
                            Id = 31,
                            ArrivalTime = new TimeSpan(0, 10, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 2, 0, 0),
                            StopId = 1,
                            TrainScheduleId = 11
                        },
                        new
                        {
                            Id = 32,
                            ArrivalTime = new TimeSpan(0, 10, 15, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 17, 0, 0),
                            StopId = 2,
                            TrainScheduleId = 11
                        },
                        new
                        {
                            Id = 33,
                            ArrivalTime = new TimeSpan(0, 10, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 32, 0, 0),
                            StopId = 3,
                            TrainScheduleId = 11
                        },
                        new
                        {
                            Id = 34,
                            ArrivalTime = new TimeSpan(0, 10, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 2, 0, 0),
                            StopId = 1,
                            TrainScheduleId = 12
                        },
                        new
                        {
                            Id = 35,
                            ArrivalTime = new TimeSpan(0, 10, 15, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 17, 0, 0),
                            StopId = 2,
                            TrainScheduleId = 12
                        },
                        new
                        {
                            Id = 36,
                            ArrivalTime = new TimeSpan(0, 10, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 32, 0, 0),
                            StopId = 3,
                            TrainScheduleId = 12
                        },
                        new
                        {
                            Id = 37,
                            ArrivalTime = new TimeSpan(0, 10, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 2, 0, 0),
                            StopId = 1,
                            TrainScheduleId = 13
                        },
                        new
                        {
                            Id = 38,
                            ArrivalTime = new TimeSpan(0, 10, 15, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 17, 0, 0),
                            StopId = 2,
                            TrainScheduleId = 13
                        },
                        new
                        {
                            Id = 39,
                            ArrivalTime = new TimeSpan(0, 10, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 32, 0, 0),
                            StopId = 3,
                            TrainScheduleId = 13
                        },
                        new
                        {
                            Id = 40,
                            ArrivalTime = new TimeSpan(0, 10, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 2, 0, 0),
                            StopId = 1,
                            TrainScheduleId = 14
                        },
                        new
                        {
                            Id = 41,
                            ArrivalTime = new TimeSpan(0, 10, 15, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 17, 0, 0),
                            StopId = 2,
                            TrainScheduleId = 14
                        },
                        new
                        {
                            Id = 42,
                            ArrivalTime = new TimeSpan(0, 10, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 32, 0, 0),
                            StopId = 3,
                            TrainScheduleId = 14
                        },
                        new
                        {
                            Id = 43,
                            ArrivalTime = new TimeSpan(0, 8, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 8, 2, 0, 0),
                            StopId = 4,
                            TrainScheduleId = 15
                        },
                        new
                        {
                            Id = 44,
                            ArrivalTime = new TimeSpan(0, 9, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 9, 32, 0, 0),
                            StopId = 5,
                            TrainScheduleId = 15
                        },
                        new
                        {
                            Id = 45,
                            ArrivalTime = new TimeSpan(0, 10, 45, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 47, 0, 0),
                            StopId = 6,
                            TrainScheduleId = 15
                        },
                        new
                        {
                            Id = 46,
                            ArrivalTime = new TimeSpan(0, 8, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 8, 2, 0, 0),
                            StopId = 4,
                            TrainScheduleId = 16
                        },
                        new
                        {
                            Id = 47,
                            ArrivalTime = new TimeSpan(0, 9, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 9, 32, 0, 0),
                            StopId = 5,
                            TrainScheduleId = 16
                        },
                        new
                        {
                            Id = 48,
                            ArrivalTime = new TimeSpan(0, 10, 45, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 47, 0, 0),
                            StopId = 6,
                            TrainScheduleId = 16
                        },
                        new
                        {
                            Id = 49,
                            ArrivalTime = new TimeSpan(0, 8, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 8, 2, 0, 0),
                            StopId = 4,
                            TrainScheduleId = 17
                        },
                        new
                        {
                            Id = 50,
                            ArrivalTime = new TimeSpan(0, 9, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 9, 32, 0, 0),
                            StopId = 5,
                            TrainScheduleId = 17
                        },
                        new
                        {
                            Id = 51,
                            ArrivalTime = new TimeSpan(0, 10, 45, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 47, 0, 0),
                            StopId = 6,
                            TrainScheduleId = 17
                        },
                        new
                        {
                            Id = 52,
                            ArrivalTime = new TimeSpan(0, 8, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 8, 2, 0, 0),
                            StopId = 4,
                            TrainScheduleId = 18
                        },
                        new
                        {
                            Id = 53,
                            ArrivalTime = new TimeSpan(0, 9, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 9, 32, 0, 0),
                            StopId = 5,
                            TrainScheduleId = 18
                        },
                        new
                        {
                            Id = 54,
                            ArrivalTime = new TimeSpan(0, 10, 45, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 47, 0, 0),
                            StopId = 6,
                            TrainScheduleId = 18
                        },
                        new
                        {
                            Id = 55,
                            ArrivalTime = new TimeSpan(0, 8, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 8, 2, 0, 0),
                            StopId = 4,
                            TrainScheduleId = 19
                        },
                        new
                        {
                            Id = 56,
                            ArrivalTime = new TimeSpan(0, 9, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 9, 32, 0, 0),
                            StopId = 5,
                            TrainScheduleId = 19
                        },
                        new
                        {
                            Id = 57,
                            ArrivalTime = new TimeSpan(0, 10, 45, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 47, 0, 0),
                            StopId = 6,
                            TrainScheduleId = 19
                        },
                        new
                        {
                            Id = 58,
                            ArrivalTime = new TimeSpan(0, 8, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 8, 2, 0, 0),
                            StopId = 4,
                            TrainScheduleId = 20
                        },
                        new
                        {
                            Id = 59,
                            ArrivalTime = new TimeSpan(0, 9, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 9, 32, 0, 0),
                            StopId = 5,
                            TrainScheduleId = 20
                        },
                        new
                        {
                            Id = 60,
                            ArrivalTime = new TimeSpan(0, 10, 45, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 47, 0, 0),
                            StopId = 6,
                            TrainScheduleId = 20
                        },
                        new
                        {
                            Id = 61,
                            ArrivalTime = new TimeSpan(0, 8, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 8, 2, 0, 0),
                            StopId = 4,
                            TrainScheduleId = 21
                        },
                        new
                        {
                            Id = 62,
                            ArrivalTime = new TimeSpan(0, 9, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 9, 32, 0, 0),
                            StopId = 5,
                            TrainScheduleId = 21
                        },
                        new
                        {
                            Id = 63,
                            ArrivalTime = new TimeSpan(0, 10, 45, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 47, 0, 0),
                            StopId = 6,
                            TrainScheduleId = 21
                        },
                        new
                        {
                            Id = 64,
                            ArrivalTime = new TimeSpan(0, 10, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 2, 0, 0),
                            StopId = 4,
                            TrainScheduleId = 22
                        },
                        new
                        {
                            Id = 65,
                            ArrivalTime = new TimeSpan(0, 11, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 11, 32, 0, 0),
                            StopId = 5,
                            TrainScheduleId = 22
                        },
                        new
                        {
                            Id = 66,
                            ArrivalTime = new TimeSpan(0, 12, 45, 0, 0),
                            DepartureTime = new TimeSpan(0, 12, 47, 0, 0),
                            StopId = 6,
                            TrainScheduleId = 22
                        },
                        new
                        {
                            Id = 67,
                            ArrivalTime = new TimeSpan(0, 10, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 2, 0, 0),
                            StopId = 4,
                            TrainScheduleId = 23
                        },
                        new
                        {
                            Id = 68,
                            ArrivalTime = new TimeSpan(0, 11, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 11, 32, 0, 0),
                            StopId = 5,
                            TrainScheduleId = 23
                        },
                        new
                        {
                            Id = 69,
                            ArrivalTime = new TimeSpan(0, 12, 45, 0, 0),
                            DepartureTime = new TimeSpan(0, 12, 47, 0, 0),
                            StopId = 6,
                            TrainScheduleId = 23
                        },
                        new
                        {
                            Id = 70,
                            ArrivalTime = new TimeSpan(0, 10, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 2, 0, 0),
                            StopId = 4,
                            TrainScheduleId = 24
                        },
                        new
                        {
                            Id = 71,
                            ArrivalTime = new TimeSpan(0, 11, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 11, 32, 0, 0),
                            StopId = 5,
                            TrainScheduleId = 24
                        },
                        new
                        {
                            Id = 72,
                            ArrivalTime = new TimeSpan(0, 12, 45, 0, 0),
                            DepartureTime = new TimeSpan(0, 12, 47, 0, 0),
                            StopId = 6,
                            TrainScheduleId = 24
                        },
                        new
                        {
                            Id = 73,
                            ArrivalTime = new TimeSpan(0, 10, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 2, 0, 0),
                            StopId = 4,
                            TrainScheduleId = 25
                        },
                        new
                        {
                            Id = 74,
                            ArrivalTime = new TimeSpan(0, 11, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 11, 32, 0, 0),
                            StopId = 5,
                            TrainScheduleId = 25
                        },
                        new
                        {
                            Id = 75,
                            ArrivalTime = new TimeSpan(0, 12, 45, 0, 0),
                            DepartureTime = new TimeSpan(0, 12, 47, 0, 0),
                            StopId = 6,
                            TrainScheduleId = 25
                        },
                        new
                        {
                            Id = 76,
                            ArrivalTime = new TimeSpan(0, 10, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 2, 0, 0),
                            StopId = 4,
                            TrainScheduleId = 26
                        },
                        new
                        {
                            Id = 77,
                            ArrivalTime = new TimeSpan(0, 11, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 11, 32, 0, 0),
                            StopId = 5,
                            TrainScheduleId = 26
                        },
                        new
                        {
                            Id = 78,
                            ArrivalTime = new TimeSpan(0, 12, 45, 0, 0),
                            DepartureTime = new TimeSpan(0, 12, 47, 0, 0),
                            StopId = 6,
                            TrainScheduleId = 26
                        },
                        new
                        {
                            Id = 79,
                            ArrivalTime = new TimeSpan(0, 10, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 2, 0, 0),
                            StopId = 4,
                            TrainScheduleId = 27
                        },
                        new
                        {
                            Id = 80,
                            ArrivalTime = new TimeSpan(0, 11, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 11, 32, 0, 0),
                            StopId = 5,
                            TrainScheduleId = 27
                        },
                        new
                        {
                            Id = 81,
                            ArrivalTime = new TimeSpan(0, 12, 45, 0, 0),
                            DepartureTime = new TimeSpan(0, 12, 47, 0, 0),
                            StopId = 6,
                            TrainScheduleId = 27
                        },
                        new
                        {
                            Id = 82,
                            ArrivalTime = new TimeSpan(0, 10, 0, 0, 0),
                            DepartureTime = new TimeSpan(0, 10, 2, 0, 0),
                            StopId = 4,
                            TrainScheduleId = 28
                        },
                        new
                        {
                            Id = 83,
                            ArrivalTime = new TimeSpan(0, 11, 30, 0, 0),
                            DepartureTime = new TimeSpan(0, 11, 32, 0, 0),
                            StopId = 5,
                            TrainScheduleId = 28
                        },
                        new
                        {
                            Id = 84,
                            ArrivalTime = new TimeSpan(0, 12, 45, 0, 0),
                            DepartureTime = new TimeSpan(0, 12, 47, 0, 0),
                            StopId = 6,
                            TrainScheduleId = 28
                        });
                });

            modelBuilder.Entity("TrainTrackingService.Models.TrainPosition", b =>
                {
                    b.Property<string>("TrainId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CurrentStop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("ETA")
                        .HasColumnType("time");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("NextStop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("NextStopETA")
                        .HasColumnType("time");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("TrainId");

                    b.ToTable("TrainPositions");
                });

            modelBuilder.Entity("TrainTrackingService.Models.TrainRoute", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LineColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TrainRoute");

                    b.HasData(
                        new
                        {
                            Id = "CT1",
                            LineColor = "#1abc9c",
                            RouteName = "Cape Town - Bellville"
                        },
                        new
                        {
                            Id = "CT2",
                            LineColor = "#e67e22",
                            RouteName = "Cape Town - Simon's Town"
                        });
                });

            modelBuilder.Entity("TrainTrackingService.Models.TrainSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrainId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("TrainSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayOfWeek = 0,
                            RouteId = "CT1",
                            TrainId = "CT1-T1"
                        },
                        new
                        {
                            Id = 2,
                            DayOfWeek = 1,
                            RouteId = "CT1",
                            TrainId = "CT1-T1"
                        },
                        new
                        {
                            Id = 3,
                            DayOfWeek = 2,
                            RouteId = "CT1",
                            TrainId = "CT1-T1"
                        },
                        new
                        {
                            Id = 4,
                            DayOfWeek = 3,
                            RouteId = "CT1",
                            TrainId = "CT1-T1"
                        },
                        new
                        {
                            Id = 5,
                            DayOfWeek = 4,
                            RouteId = "CT1",
                            TrainId = "CT1-T1"
                        },
                        new
                        {
                            Id = 6,
                            DayOfWeek = 5,
                            RouteId = "CT1",
                            TrainId = "CT1-T1"
                        },
                        new
                        {
                            Id = 7,
                            DayOfWeek = 6,
                            RouteId = "CT1",
                            TrainId = "CT1-T1"
                        },
                        new
                        {
                            Id = 8,
                            DayOfWeek = 0,
                            RouteId = "CT1",
                            TrainId = "CT1-T2"
                        },
                        new
                        {
                            Id = 9,
                            DayOfWeek = 1,
                            RouteId = "CT1",
                            TrainId = "CT1-T2"
                        },
                        new
                        {
                            Id = 10,
                            DayOfWeek = 2,
                            RouteId = "CT1",
                            TrainId = "CT1-T2"
                        },
                        new
                        {
                            Id = 11,
                            DayOfWeek = 3,
                            RouteId = "CT1",
                            TrainId = "CT1-T2"
                        },
                        new
                        {
                            Id = 12,
                            DayOfWeek = 4,
                            RouteId = "CT1",
                            TrainId = "CT1-T2"
                        },
                        new
                        {
                            Id = 13,
                            DayOfWeek = 5,
                            RouteId = "CT1",
                            TrainId = "CT1-T2"
                        },
                        new
                        {
                            Id = 14,
                            DayOfWeek = 6,
                            RouteId = "CT1",
                            TrainId = "CT1-T2"
                        },
                        new
                        {
                            Id = 15,
                            DayOfWeek = 0,
                            RouteId = "CT2",
                            TrainId = "CT2-T1"
                        },
                        new
                        {
                            Id = 16,
                            DayOfWeek = 1,
                            RouteId = "CT2",
                            TrainId = "CT2-T1"
                        },
                        new
                        {
                            Id = 17,
                            DayOfWeek = 2,
                            RouteId = "CT2",
                            TrainId = "CT2-T1"
                        },
                        new
                        {
                            Id = 18,
                            DayOfWeek = 3,
                            RouteId = "CT2",
                            TrainId = "CT2-T1"
                        },
                        new
                        {
                            Id = 19,
                            DayOfWeek = 4,
                            RouteId = "CT2",
                            TrainId = "CT2-T1"
                        },
                        new
                        {
                            Id = 20,
                            DayOfWeek = 5,
                            RouteId = "CT2",
                            TrainId = "CT2-T1"
                        },
                        new
                        {
                            Id = 21,
                            DayOfWeek = 6,
                            RouteId = "CT2",
                            TrainId = "CT2-T1"
                        },
                        new
                        {
                            Id = 22,
                            DayOfWeek = 0,
                            RouteId = "CT2",
                            TrainId = "CT2-T2"
                        },
                        new
                        {
                            Id = 23,
                            DayOfWeek = 1,
                            RouteId = "CT2",
                            TrainId = "CT2-T2"
                        },
                        new
                        {
                            Id = 24,
                            DayOfWeek = 2,
                            RouteId = "CT2",
                            TrainId = "CT2-T2"
                        },
                        new
                        {
                            Id = 25,
                            DayOfWeek = 3,
                            RouteId = "CT2",
                            TrainId = "CT2-T2"
                        },
                        new
                        {
                            Id = 26,
                            DayOfWeek = 4,
                            RouteId = "CT2",
                            TrainId = "CT2-T2"
                        },
                        new
                        {
                            Id = 27,
                            DayOfWeek = 5,
                            RouteId = "CT2",
                            TrainId = "CT2-T2"
                        },
                        new
                        {
                            Id = 28,
                            DayOfWeek = 6,
                            RouteId = "CT2",
                            TrainId = "CT2-T2"
                        });
                });

            modelBuilder.Entity("TrainTrackingService.Models.TrainStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("DistanceFromStart")
                        .HasColumnType("float");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StopOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("TrainStops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DistanceFromStart = 0.0,
                            Latitude = -33.925800000000002,
                            Longitude = 18.423200000000001,
                            RouteId = "CT1",
                            StationName = "Cape Town",
                            StopOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            DistanceFromStart = 3.5,
                            Latitude = -33.928100000000001,
                            Longitude = 18.455100000000002,
                            RouteId = "CT1",
                            StationName = "Salt River",
                            StopOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            DistanceFromStart = 22.5,
                            Latitude = -33.899099999999997,
                            Longitude = 18.629799999999999,
                            RouteId = "CT1",
                            StationName = "Bellville",
                            StopOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            DistanceFromStart = 0.0,
                            Latitude = -33.925800000000002,
                            Longitude = 18.423200000000001,
                            RouteId = "CT2",
                            StationName = "Cape Town",
                            StopOrder = 1
                        },
                        new
                        {
                            Id = 5,
                            DistanceFromStart = 27.5,
                            Latitude = -34.1051,
                            Longitude = 18.4697,
                            RouteId = "CT2",
                            StationName = "Muizenberg",
                            StopOrder = 7
                        },
                        new
                        {
                            Id = 6,
                            DistanceFromStart = 43.5,
                            Latitude = -34.193100000000001,
                            Longitude = 18.432600000000001,
                            RouteId = "CT2",
                            StationName = "Simon's Town",
                            StopOrder = 12
                        });
                });

            modelBuilder.Entity("TrainTrackingService.Models.ScheduleStop", b =>
                {
                    b.HasOne("TrainTrackingService.Models.TrainStop", "Stop")
                        .WithMany()
                        .HasForeignKey("StopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TrainTrackingService.Models.TrainSchedule", null)
                        .WithMany("Stops")
                        .HasForeignKey("TrainScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stop");
                });

            modelBuilder.Entity("TrainTrackingService.Models.TrainSchedule", b =>
                {
                    b.HasOne("TrainTrackingService.Models.TrainRoute", "Route")
                        .WithMany("Schedules")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("TrainTrackingService.Models.TrainStop", b =>
                {
                    b.HasOne("TrainTrackingService.Models.TrainRoute", "Route")
                        .WithMany("Stops")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("TrainTrackingService.Models.TrainRoute", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Stops");
                });

            modelBuilder.Entity("TrainTrackingService.Models.TrainSchedule", b =>
                {
                    b.Navigation("Stops");
                });
#pragma warning restore 612, 618
        }
    }
}
